name = "Hugo Profile"
license = "MIT"
licenselink = "https://github.com/viz-graffito/vijit-portfolio/blob/main/LICENSE"
description = "A high performance and mobile first hugo template for personal portfolio and blog."
homepage = "https://github.com/ROHANPATAKAR/vijit-portfolio"
tags = ["Responsive","Blog", "Portfolio", "Personal"]
min_version = "0.68.0"

[author]
  name = "VIJIT SINGH"
  homepage = "https://www.linkedin.com/in/viz-graffito/"
